name: Upload AI Recommendations to EC2

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Archive repository into ./build folder (excluding unnecessary files)
        run: |
          mkdir -p build
          rsync -av \
            --exclude='.git' \
            --exclude='build' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='*.pyo' \
            --exclude='*.log' \
            --exclude='.DS_Store' \
            --exclude='.env' \
            ./ ./build/

      - name: Upload to EC2 ~/infra/ai-recommendations/
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          source: "build/*"
          target: "~/infra/ai-recommendations/"

      - name: Restart Docker Compose for AI
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_CI_KEY }}
          script: |
            cd ~/infra
            docker compose down
            docker builder prune -af
            docker image prune -af
            docker compose up -d --build
